services:
  redirect-service:
    build: .
    env_file:
      - .env.production
    depends_on:
      redis:
        condition: service_healthy
    networks:
       - url-shortener-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirect-service.rule=Host(`localhost`) && PathPrefix(`/r`)" 
      - "traefik.http.routers.redirect-service.entrypoints=web"
      - "traefik.http.routers.redirect-service.middlewares=redirect-stripprefix"
      - "traefik.http.middlewares.redirect-stripprefix.stripprefix.prefixes=/r"
      - "traefik.http.services.redirect-service.loadbalancer.server.port=8080"

networks:
  url-shortener-net: 
    attachable: true
    name: url-shortener-net