services:
  redirect-service1:
    build: .
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
       - url-shortener-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirect-service.rule=Host(`localhost`) && PathPrefix(`/r`)" 
      - "traefik.http.routers.redirect-service.entrypoints=web"
      - "traefik.http.routers.redirect-service.middlewares=redirect-stripprefix"
      - "traefik.http.middlewares.redirect-stripprefix.stripprefix.prefixes=/r"
      - "traefik.http.services.redirect-service.loadbalancer.server.port=8080"
  redirect-service2:
    build: .
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    networks:
       - url-shortener-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redirect-service.rule=Host(`localhost`) && PathPrefix(`/r`)" 
      - "traefik.http.routers.redirect-service.entrypoints=web"
      - "traefik.http.routers.redirect-service.middlewares=redirect-stripprefix"
      - "traefik.http.middlewares.redirect-stripprefix.stripprefix.prefixes=/r"
      - "traefik.http.services.redirect-service.loadbalancer.server.port=8080"
  redis:
    image: "redis:alpine"
    networks:
      - url-shortener-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  url-shortener-net: 
    external: true