apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redirect-service-ingress
  namespace: url-shortener
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: url-shortener-redirect-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: localhost.com
    http:
      paths:
      - path: /r
        pathType: Prefix
        backend:
          service:
            name: redirect-service
            port:
              name: http