apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: url-shortener
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID_HERE"
  GOOGLE_CLIENT_SECRET: "YOUR_GOOGLE_CLIENT_SECRET_HERE"

  JWT_SECRET: "YOUR_JWT_SECRET_HERE"

  FRONTEND_URL: "YOUR_FRONTEND_URL_HERE" #get from minikube service front-end-service --url -n url-shortener