server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email

management:
  endpoints:
    web:
      exposure:
        include: health # Chỉ cho phép truy cập endpoint /health
  endpoint:
    health:
      show-details: always # Luôn hiển thị chi tiết

jwt:
  secret: ${JWT_SECRET:abcdef} # Secret key cho JWT
  expiration-ms: 86400000 # 1 ngày