apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: front-end:latest # Sử dụng image đã build
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: front-end-secret
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: url-shortener
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30030